version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: ['pm2-runtime', 'start', 'ecosystem.config.js']
