export const USER_MESSAGE = {
  VALIDATION_ERROR: 'Validation error',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_STRING: 'Name must be string',
  NAME_LENGTH_MUST_BE_MORE_THAN_6: 'Name length must be more than 6',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_IS_INVALID: 'Password is invalid',
  PASSWORD_MUST_BE_STRING: 'Password must be string',
  PASSWORD_CONFIRM_IS_REQUIRED: 'Password confirm is required',
  PASSWORD_CONFIRM_IS_INVALID: 'Password confirm is invalid',
  PASSWORD_LENGTH_MUST_BE_MORE_THAN_6: 'Password length must be more than 6',
  PASSWORD_MUST_BE_STRONG: 'Password must be strong',
  PASSWORD_CONFIRM_MUST_BE_STRONG: 'Password confirm must be strong',
  PASSWORD_CONFIRM_MUST_BE_EQUAL_TO_PASSWORD: 'Password confirm must be equal to password',
  PASSWORD_CONFIRM_MUST_BE_STRING: 'Password confirm must be string',
  PASSWORD_CONFIRM_MUST_BE_THE_SAME_AS_PASSWORD: 'Password confirm must be the same as password',
  DAY_OF_BIRTH_MUST_BE_ISO8610: 'Day of birth must be ISO8610',
  LOGIN_SUCCESSFULLY: 'Login successfully',
  REGISTER_SUCCESSFULLY: 'Register successfully',
  EMAIL_OR_PASSWORD_IS_INCORRECT: 'Email or password is incorrect',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_IS_STRING: 'Refresh token must be string',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  USED_REFRESH_TOKEN_OR_NOT_EXISTS: 'Used refresh token or not exists',
  LOGOUT_SUCCESSFULLY: 'Logout successfully',
  ACCESS_TOKEN_IS_INVALID: 'Access token is invalid',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email already verified before',
  EMAIL_VERIFY_SUCCESSFULLY: 'Email verify successfully',
  RESEND_EMAIL_VERIFY_SUCCESSFULLY: 'Resend email verify successfully',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  VERIFY_FORGOT_PASSWORD_SUCCESSFULLY: 'Verify forgot password successfully',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Forgot password token is invalid',
  RESET_PASSWORD_SUCCESSFULLY: 'Reset password successfully',
  GET_ME_SUCCESSFULLY: 'Get me profile successfully',
  USER_NOT_VERIFIED: 'User not verified',
  BIO_MUST_BE_STRING: 'Bio must be string',
  BIO_LENGTH_MUST_BE_MORE_THAN_1_AND_LESS_THAN_200: 'Bio length must be more than 1 and less than 200',
  LOCATION_MUST_BE_STRING: 'Location must be string',
  LOCATION_LENGTH: 'Location length must be less than 200',
  WEBSITE_MUST_BE_STRING: 'Website must be string',
  WEBSITE_LENGTH: 'Website length must be less than 200',
  USERNAME_LENGTH: 'Username length must be more than 6 and less than 50',
  AVATAR_MUST_BE_STRING: 'Avatar must be string',
  AVATAR_LENGTH: 'Avatar length must be less than 200',
  CONVER_PHOTO_MUST_BE_STRING: 'Conver photo must be string',
  CONVER_PHOTO_LENGTH: 'Conver photo length must be less than 200',
  UPDATE_ME_SUCCESSFULLY: 'Update me successfully',
  GET_PROFILE_SUCCESSFULLY: 'Get profile successfully',
  FOLLOW_SUCCESSFULLY: 'Follow successfully',
  INVALID_FOLLOWED_USER_ID: 'Invalid followed user id',
  FOLLOWED: 'Followed',
  INVALID_USER_ID: 'Invalid user id',
  UNFOLLOW_SUCCESSFULLY: 'Unfollow successfully',
  ALREADY_UNFOLLOWED: 'Already unfollowed',
  USERNAME_IS_INVALID: 'Username is invalid',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  OLD_PASSWORD_IS_INCORRECT: 'Old password is incorrect',
  CHANGE_PASSWORD_SUCCESSFULLY: 'Change password successfully',
  GMAIL_NOT_VERIFIED: 'Gmail not verified',
  UPLOAD_SUCCESSFULLY: 'Upload successfully',
  REFRESH_TOKEN_SUCCESSFULLY: 'Refresh token successfully'
}

export const TWEET_MESSAGE = {
  TYPE_IS_REQUIRED: 'Type is required',
  TYPE_IS_INVALID: 'Type is invalid',
  TYPE_MUST_BE_STRING: 'Type must be string',
  TYPE_MUST_BE_ONE_OF_THE_FOLLOWING_VALUES: 'Type must be one of the following values',
  AUDIENCE_IS_REQUIRED: 'Audience is required',
  AUDIENCE_IS_INVALID: 'Audience is invalid',
  AUDIENCE_MUST_BE_STRING: 'Audience must be string',
  AUDIENCE_MUST_BE_ONE_OF_THE_FOLLOWING_VALUES: 'Audience must be one of the following values',
  CONTENT_IS_REQUIRED: 'Content is required',
  CONTENT_MUST_BE_STRING: 'Content must be string',
  CONTENT_LENGTH_MUST_BE_MORE_THAN_1_AND_LESS_THAN_280: 'Content length must be more than 1 and less than 280',
  PARENT_ID_IS_INVALID: 'Parent id is invalid',
  PARENT_ID_MUST_BE_STRING: 'Parent id must be string',
  HASHTAGS_MUST_BE_ARRAY: 'Hashtags must be array',
  HASHTAGS_MUST_BE_STRING: 'Hashtags must be string',
  HASHTAGS_LENGTH_MUST_BE_MORE_THAN_1_AND_LESS_THAN_50: 'Hashtags length must be more than 1 and less than 50',
  MENTIONS_MUST_BE_ARRAY: 'Mentions must be array',
  MENTIONS_MUST_BE_STRING: 'Mentions must be string',
  MENTIONS_LENGTH_MUST_BE_MORE_THAN_1_AND_LESS_THAN_50: 'Mentions length must be more than 1 and less than 50',
  MEDIAS_MUST_BE_ARRAY: 'Medias must be array',
  MEDIAS_MUST_BE_STRING: 'Medias must be string',
  MEDIAS_LENGTH_MUST_BE_MORE_THAN_1_AND_LESS_THAN_4: 'Medias length must be more than 1 and less than 4',
  CREATE_TWEET_SUCCESSFULLY: 'Create tweet successfully',
  GET_TWEETS_SUCCESSFULLY: 'Get tweets successfully',
  GET_TWEET_SUCCESSFULLY: 'Get tweet successfully',
  TWEET_NOT_FOUND: 'Tweet not found',
  DELETE_TWEET_SUCCESSFULLY: 'Delete tweet successfully',
  GET_COMMENTS_SUCCESSFULLY: 'Get comments successfully',
  GET_RETWEETS_SUCCESSFULLY: 'Get retweets successfully',
  PARENT_ID_MUST_BE_A_VALID_TWEET_ID: 'Parent id must be a valid tweet id',
  PARENT_ID_MUST_BE_NULL: 'Parent id must be null',
  CONTENT_MUST_BE_A_NON_EMPTY_STRING: 'Content must be a non-empty string',
  CONTENT_MUST_BE_EMPTY_STRING: 'Content must be empty string',
  HASHTAGS_MUST_BE_AN_ARRAY_STRING: 'Hashtags must be an array string',
  MENTIONS_MUST_BE_AN_ARRAY_OF_USER_ID: 'Mentions must be an array of user id',
  MEDIAS_MUST_BE_AN_ARRAY_OF_MEDIA_OBJECT: 'Medias must be an array of media object',
  TWEET_ID_IS_INVALID: 'Tweet id is invalid',
  TWEET_IS_NOT_PUBLIC: 'Tweet is not public'
} as const

export const BOOKMARK_MESSAGE = {
  CREATE_BOOKMARK_SUCCESSFULLY: 'Create bookmark successfully',
  DELETE_BOOKMARK_SUCCESSFULLY: 'Delete bookmark successfully',
  GET_BOOKMARKS_SUCCESSFULLY: 'Get bookmarks successfully',
  DELETE_BOOKMARK_BY_BOOKMARK_ID_SUCCESSFULLY: 'Delete bookmark by bookmark id successfully'
} as const

export const LIKE_MESSAGE = {
  LIKE_TWEET_SUCCESSFULLY: 'Like tweet successfully',
  UNLIKE_TWEET_SUCCESSFULLY: 'Unlike tweet successfully'
} as const
