export const USER_MESSAGE = {
  VALIDATION_ERROR: 'Validation error',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_STRING: 'Name must be string',
  NAME_LENGTH_MUST_BE_MORE_THAN_6: 'Name length must be more than 6',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_IS_INVALID: 'Password is invalid',
  PASSWORD_MUST_BE_STRING: 'Password must be string',
  PASSWORD_CONFIRM_IS_REQUIRED: 'Password confirm is required',
  PASSWORD_CONFIRM_IS_INVALID: 'Password confirm is invalid',
  PASSWORD_LENGTH_MUST_BE_MORE_THAN_6: 'Password length must be more than 6',
  PASSWORD_MUST_BE_STRONG: 'Password must be strong',
  PASSWORD_CONFIRM_MUST_BE_STRONG: 'Password confirm must be strong',
  PASSWORD_CONFIRM_MUST_BE_EQUAL_TO_PASSWORD: 'Password confirm must be equal to password',
  PASSWORD_CONFIRM_MUST_BE_STRING: 'Password confirm must be string',
  PASSWORD_CONFIRM_MUST_BE_THE_SAME_AS_PASSWORD: 'Password confirm must be the same as password',
  DAY_OF_BIRTH_MUST_BE_ISO8610: 'Day of birth must be ISO8610',
  LOGIN_SUCCESSFULLY: 'Login successfully',
  REGISTER_SUCCESSFULLY: 'Register successfully',
  EMAIL_OR_PASSWORD_IS_INCORRECT: 'Email or password is incorrect',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_IS_STRING: 'Refresh token must be string',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  USED_REFRESH_TOKEN_OR_NOT_EXISTS: 'Used refresh token or not exists',
  LOGOUT_SUCCESSFULLY: 'Logout successfully'
}
